### ISSUE TITLE
Allow subsampling factor to be specified

### ISSUE THREAD

**Issue by abaldur** [gfwilliams/svgtoeagle#13]
If a small circle is converted, it becomes very edged:
![image](https://user-images.githubusercontent.com/19939339/61587595-51a4bd00-ab8d-11e9-8a56-d5786c7d7af0.png)

**Comment by EmbeddedMan** [comment]
This is really critical - the default subsampling value is good for many SVGs, but not all. Allowing it to be specified would give the user the control needed.
![image](https://user-images.githubusercontent.com/450056/78465157-a48cb900-76b7-11ea-9fd9-149a10747e28.png)
This is with a subsampling value of 2.
![image](https://user-images.githubusercontent.com/450056/78465196-faf9f780-76b7-11ea-89cf-14b12c33e6a7.png)
This is with a subsampling value of 10.
![image](https://user-images.githubusercontent.com/450056/78465217-398fb200-76b8-11ea-9109-ba9e6c8a977e.png)
And this is with a subsampling value of 25, which faithfully reproduces the original SVG artwork.

**Comment by gfwilliams** [comment]
I should mention that actually this is a side-effect of just using `getPointAtLength` in a brute-force way: https://github.com/gfwilliams/svgtoeagle/blob/master/svgtoeagle.js#L243

It's far from ideal, since it doesn't handle sharp corners properly at all, and getting a high res polyline from it takes *ages* and loads of memory. It'd be much better if the coordinates could be retrieved using something like https://stackoverflow.com/a/34883305/1215872 - but you do then have to be able to handle beziers I think.

**Comment by EmbeddedMan** [comment]
Ahh. Very interesting. I don't know any JavaScript, so I'm not in a good position to do major changes like that. I'll live with loads of memory and long conversion time for now. I was just super happy to be able to change a parameter that made my conversion look so good.

**Comment by gfwilliams** [comment]
This code had just been posted up for converting SVGs to JS code for Espruino: https://github.com/nebbishhacker/svg2bangle

It actually properly decodes the SVG path data: https://github.com/nebbishhacker/svg2bangle/blob/master/svg2bangle.js#L57

It'd produce far better paths than my getPointAtLength implementation

**Comment by EmbeddedMan** [comment]
@gfwilliams  I think you can resolve this issue now.

**Comment by gfwilliams** [comment]
Thanks :)
